version: 2

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: apt-get
          command: sudo apt-get update && sudo apt-get -y install lcov ruby
      - run:
          name: rustup version
          command: rustup --version
      - run:
          name: rustup install nightly
          command: rustup install nightly
      - run:
          name: rustup component add
          command: rustup component add clippy rustfmt
      - run:
          name: fmt
          command: cargo fmt -- --check
      - run:
          name: cargo install grcov
          command: |
            sudo gem install coveralls-lcov
            cargo install grcov
      - restore_cache:
          keys:
            - v1-cargo-lock-{{ checksum "Cargo.lock" }}
      - run:
          name: build
          command: cargo build
      - run:
          name: lint
          command: cargo clippy
      - save_cache:
          key: v1-cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo/registry"
            - "target"
      - run:
          name: test
          command: cargo test
      - run:
          name: generate coverage
          command: |
            sh coverage.sh
            bash <(curl -s https://codecov.io/bash) -f lcov.info;
